// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {appstate} from '../models';
import {steam} from '../models';
import {logs} from '../models';
import {sound} from '../models';

export function AppAddr():Promise<string>;

export function Config():Promise<config.Config>;

export function Error():Promise<appstate.AppError>;

export function Games():Promise<Array<steam.GameInfo>>;

export function LaunchOptions(arg1:steam.ID,arg2:steam.ID):Promise<string>;

export function Log(arg1:logs.APILog):Promise<void>;

export function Presence():Promise<appstate.Presence>;

export function Profile(arg1:steam.ID,arg2:string):Promise<steam.Profile>;

export function ServerInfo(arg1:steam.Region,arg2:string):Promise<steam.ServerInfo>;

export function Servers(arg1:steam.ID):Promise<{[key: string]: steam.Region}>;

export function Sounds():Promise<Array<sound.SoundInfo>>;

export function State():Promise<appstate.AppState>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
