// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Env():Promise<main.Environment>;

export function Error():Promise<main.AppError>;

export function Games():Promise<Array<main.GameInfo>>;

export function InGame(arg1:number):Promise<main.InGame>;

export function Log(arg1:Array<any>):Promise<void>;

export function Presence():Promise<main.Presence>;

export function Sounds():Promise<Array<main.SoundInfo>>;

export function State():Promise<main.AppState>;
