// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppAddr() {
  return window['go']['main']['API']['AppAddr']();
}

export function Config() {
  return window['go']['main']['API']['Config']();
}

export function Env() {
  return window['go']['main']['API']['Env']();
}

export function Error() {
  return window['go']['main']['API']['Error']();
}

export function Games() {
  return window['go']['main']['API']['Games']();
}

export function InGame(arg1) {
  return window['go']['main']['API']['InGame'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['API']['Log'](arg1);
}

export function Presence() {
  return window['go']['main']['API']['Presence']();
}

export function Profile(arg1, arg2) {
  return window['go']['main']['API']['Profile'](arg1, arg2);
}

export function ServerInfo(arg1, arg2) {
  return window['go']['main']['API']['ServerInfo'](arg1, arg2);
}

export function Servers(arg1) {
  return window['go']['main']['API']['Servers'](arg1);
}

export function Sounds() {
  return window['go']['main']['API']['Sounds']();
}

export function State() {
  return window['go']['main']['API']['State']();
}
